// skills-client-integration/skills-int-client-ng16/src/app/app.component.ts
/*
Copyright 2020 SkillTree

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'skills-int-client-ng';
}

// skills-client-integration/skills-example-client-react/src/App.js
/*
 * Copyright 2020 SkillTree
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import React from 'react';
import Navigation from "./skillsDisplay/Navigation";
import './App.css';
import {
    HashRouter as Router,
    Switch,
    Route,
} from "react-router-dom";
import ShowSkills from "./skillsDisplay/ShowSkills";
import ReportSkill from "./skillsDisplay/ReportSkill";

export default function App() {
  return (
    <Router>
      <div className="App">
        <Navigation projectId="movies"/>
      </div>
      <Switch>
        <Route exact path="/showSkills">
          <ShowSkills/>
        </Route>
        <Route exact path="/">
          <ReportSkill/>
        </Route>
          {/*<Route exact path="/reportSkillEvent">
        </Route>*/}
      </Switch>
    </Router>
  );
}
