// skills-client-integration/skills-int-client-ng/src/app/components/navigation/navigation.component.ts
/*
Copyright 2020 SkillTree

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {

  constructor(public route: ActivatedRoute) { 
  }

  ngOnInit(): void {
  }

}

<!--
Copyright 2020 SkillTree

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<div>
  <div>
    <nav class="navbar navbar-dark bg-info">
      <a href="/reportSkills" class="navbar-brand">Angular Integration Examples</a>

      <ul class="navbar-nav flex-row mr-auto">
        <li [routerLinkActive]="['active']" class="nav-item active pr-3">
          <a class="nav-link" routerLink="/reportSkills" data-cy=reportSkillsLink>Report Skill Events</a>
        </li>
        <li [routerLinkActive]="['active']" class="nav-item pr-3">
          <a class="nav-link" routerLink="/showSkills" data-cy=showSkillsLink>User Display</a>
        </li>
      </ul>
      <button type="button" class="btn btn-primary">
        <span id="skillLevel"></span>
        <skills-level></skills-level>
      </button>
    </nav>
  </div>
</div>

// skills-client-integration/skills-int-client-vue/src/components/Navigation.vue
/*
Copyright 2020 SkillTree

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
<template>
    <div>
        <b-navbar type="dark" variant="info">
            <b-navbar-brand href="#">Vue.js Integration Examples</b-navbar-brand>

            <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

            <b-collapse id="nav-collapse" is-nav>
                <b-navbar-nav>
                    <b-nav-item href="#" to="/">Report Skill Events</b-nav-item>
                    <b-nav-item href="#" to="/showSkills">User Display</b-nav-item>
                </b-navbar-nav>
            </b-collapse>
            <button
              @click="$router.push('/showSkills')"
              class="btn btn-primary"><skills-level /></button>
        </b-navbar>

    </div>
</template>

<script>
    import { SkillsLevel } from '@skills/skills-client-vue';

    export default {
        components: {
            SkillsLevel,
        },
        data() {
            return {
                token: '',
                version: 0,
                projectId: 'movies',
                serviceUrl: 'http://localhost:8080',
                authenticationUrl: 'http://localhost:8090/api/users/user1/token',
            };
        },
    }
</script>

<style scoped>

</style>
